<a href="https://colab.research.google.com/github/gitmystuff/INFO5737/blob/main/Network_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Network Analysis



## Network Review

### OSI and TCP/IP 5 Layer Models

* https://www.imperva.com/learn/application-security/osi-model/
* https://microchipdeveloper.com/tcpip:tcp-ip-five-layer-model




### Protocols

https://www.guru99.com/layers-of-osi-model.html

* Physical: Ethernet hub, repeater
* Data Link: Ethernet switch, MAC
* Network: IP, ICMP
* Transport: TCP, UDP
* Session: Sockets, API sessions - allows an application to accomplish certain high-level communications over the network easily
* Presentation: PNG, GIF, PDF, translate, encrypt
* HTTP, SMTP



### Access Control and Authentication

* Firewalls
* Access control lists
* Multifactor authentication



### Intrusion Detection and Pattern Mining

* Aggregating Sessions
* Time Series?
* Packet sniffing
* Encryption
* TCP three-way handshake - https://www.techopedia.com/definition/10339/three-way-handshake, https://wiki.wireshark.org/TCP_3_way_handshaking.md
* TLS handshake - https://www.cloudflare.com/learning/ssl/what-happens-in-a-tls-handshake/



### KDD99 Dataset vs Packet

* https://www.researchgate.net/profile/Jill-Slay/publication/290061926_The_evaluation_of_Network_Anomaly_Detection_Systems_Statistical_analysis_of_the_UNSW-NB15_data_set_and_the_comparison_with_the_KDD99_data_set/links/59d9cf58aca272e6096bbfcb/The-evaluation-of-Network-Anomaly-Detection-Systems-Statistical-analysis-of-the-UNSW-NB15-data-set-and-the-comparison-with-the-KDD99-data-set.pdf

## Analyzing Network Traffic

NSL-KDD dataset is used as a network intrusion detection dataset. We will be doing one analysis using the provided labels and then another analysis ignoring the labels.

* http://kdd.ics.uci.edu/databases/kddcup99/kddcup99.html
* https://kdd.ics.uci.edu/databases/kddcup99/task.html
* Machine Learning and Security: Protecting Systems with Data and Algorithms by Clarence Chio and David Freeman
* https://www.oreilly.com/library/view/machine-learning-and/9781491979891/

Classifiers are only as good as the data used to train them.

### The Machine Learning Lifecycle

* Identify the problem
* Identify the data source
* Identify independent / dependend variables
* Split data before processing ???
* Identify duplicate features, highly correlated features, outliers, data validity, missingness
* Explore the data (EDA)
* Feature engineering and selection
* One-hot encoding
* Scaling
* Over / under sampling
* Split data ???
* Identify model assumptions
* Build model
* Test model
* Tune model
* Cross validate
* Adjust bias-variance (tradeoff)
* Adjust overfitting / underfitting
* Predict
* Deploy

https://www.analyticsvidhya.com/blog/2021/05/machine-learning-life-cycle-explained/

### Data Structures

https://docs.python.org/3/tutorial/datastructures.html

### Dictionary and DefaultDict

https://www.geeksforgeeks.org/defaultdict-in-python/

In [1]:
import os
os.environ['OMP_NUM_THREADS'] = '1'
import requests

url = 'https://raw.githubusercontent.com/gitmystuff/Linkables/main/kdd99cup_attack_types.txt'


In [2]:
from collections import defaultdict
import requests


In [3]:
# attack mapping


In [4]:
import requests

url = 'https://raw.githubusercontent.com/gitmystuff/Linkables/main/kddcup.names.txt'


In [5]:
# get continuous and symbolic features (categorical)
feature_names = defaultdict(list)



### Continuous vs Discrete

From https://www.statisticshowto.com/probability-and-statistics/statistics-definitions/discrete-vs-continuous-variables/ and https://www.g2.com/articles/discrete-vs-continuous-data (November 4, 2021)

* Discrete variables are countable in a finite amount of time. For example, you can count the change in your pocket and can count the money in your bank account
* Continuous variables refer to the unspecified nmber of possible measurements and are often expressed using decimal points such as random variables, line graphs, and are used in regression analysis

In [6]:
# # categorize features
# continuous_features = feature_names['continuous']
# continuous_features.remove('root_shell')
# binary_features = ['land', 'logged_in', 'root_shell', 'su_attempted', 'is_host_login', 'is_guest_login']
# nominal_features = list(set(feature_names['symbolic']) - set(binary_features))

### Pandas

pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool,
built on top of the Python programming language.

https://pandas.pydata.org/

In [7]:
# create column names


In [8]:
# import pandas as pd

# # read the nsl kddcup training dataset
# df = pd.read_csv('https://raw.githubusercontent.com/gitmystuff/Datasets/main/KDDTrain.csv', index_col=False, names=cols)


In [9]:
# check shape


In [10]:
# bar chart of attack types


In [11]:
# bar chart of categories


https://kdd.ics.uci.edu/databases/kddcup99/task.html

* DOS: denial-of-service, e.g. syn flood;
* R2L: unauthorized access from a remote machine, e.g. guessing password;
* U2R:  unauthorized access to local superuser (root) privileges, e.g., various ``buffer overflow'' attacks;
* probing: surveillance and other probing, e.g., port scanning.

In [12]:
# train test split data


In [13]:
# see data types


### One-Hot Encoding

only one of the dummy variables can have the value, thus hot

https://chrisalbon.com/code/machine_learning/preprocessing_structured_data/one-hot_encode_nominal_categorical_features/

In [14]:
# # see how many categories in each feature
# print(len(X_train.protocol_type.value_counts()))
# print(len(X_train.service.value_counts()))
# print(len(X_train.flag.value_counts()))

In [15]:
# feature encoding


In [16]:
# # using one hot encoder
# from sklearn.preprocessing import OneHotEncoder

# ohe = OneHotEncoder(categories='auto', drop='first', sparse_output=False, handle_unknown='ignore')

# cat_features = ['protocol_type']
# ohe_train = ohe.fit_transform(X_train[cat_features])
# ohe_train = pd.DataFrame(ohe_train, columns=ohe.get_feature_names_out(cat_features))
# ohe_train.index = X_train.index
# X_train = X_train.join(ohe_train)
# X_train.drop(cat_features, axis=1, inplace=True)

# ohe_test = ohe.transform(X_test[cat_features])
# ohe_test = pd.DataFrame(ohe_test, columns=ohe.get_feature_names_out(cat_features))
# ohe_test.index = X_test.index
# X_test = X_test.join(ohe_test)
# X_test.drop(cat_features, axis=1, inplace=True)

# print(X_train.info())

In [17]:
# verify shapes


In [18]:
# see the spread of our data


### Scaling

Standard Scaling:
* -3 to 3
* https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html

MinMax Scaling:
* 0 - 1
* https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html#sklearn.preprocessing.MinMaxScaler

In [19]:
# standard scaler

In [20]:
# minmaxscaler

In [21]:
# scale our data


### Decision Tree Classifier

* https://www.analyticsvidhya.com/blog/2021/04/beginners-guide-to-decision-tree-classification-using-python/

### Metrics

* Confusion Matrix: https://stackoverflow.com/questions/35178590/scikit-learn-confusion-
* Accuracy: https://developers.google.com/machine-learning/crash-course/classification/accuracy
* Zero-One Loss: https://link.springer.com/referenceworkentry/10.1007%2F978-0-387-30164-8_884

In [22]:
# check shape and null values


In [23]:
# create logistic regression model


In [24]:
# DecisionTreeClassifier model


In [25]:
# recall our attack categories


### KNeighbors

https://www.datacamp.com/community/tutorials/k-nearest-neighbor-classification-scikit-learn

k in k nearest neighbors: https://stackoverflow.com/questions/11568897/value-of-k-in-k-nearest-neighbor-algorithm

In [26]:
# from sklearn.neighbors import KNeighborsClassifier

# cls = KNeighborsClassifier(n_neighbors=1, n_jobs=-1)
# cls.fit(X_train, y_train)
# y_pred = cls.predict(X_test)

# print(confusion_matrix(y_test, y_pred))
# print(f'Error: {zero_one_loss(y_test, y_pred)}')
# print(f'Accuracy: {accuracy_score(y_test, y_pred)}')

<pre>
[[13382    11    15    12     2]
 [    8  9173     0     0     0]
 [   13     1  2343     0     0]
 [    9     0     6   208     1]
 [    3     0     0     2     6]]
Error: 0.003294304425481287
Accuracy: 0.9967056955745187
</pre>

## Imbalanced Classes

* problem with oversampling is with overfitting
* undersampling discards vast amounts of data
* popular method is to use a combination of oversampling and undersampling to minimize problems with each sampling technique

https://www.kaggle.com/rafjaa/resampling-strategies-for-imbalanced-datasets

In [27]:
# show imbalance of labels


In [28]:
# resample on train only
# from imblearn.over_sampling import SMOTE

# sm = SMOTE(random_state=42)
# X_train_sm, y_train_sm = sm.fit_resample(X_train, y_train)
# y_train_sm.value_counts()

In [29]:
# from imblearn.under_sampling import RandomUnderSampler

# mean_size = int(y_train.value_counts().sum()/len(y_train.value_counts()))
# ratio = {
#     'benign': mean_size,
#     'dos': mean_size,
#     'probe': mean_size,
#     'r21': mean_size,
#     'u2r': mean_size
# }

# rus = RandomUnderSampler(random_state=42, replacement=True)
# X_train_rus, y_train_rus = rus.fit_resample(X_train_sm, y_train_sm)
# print(y_train_rus.value_counts())

In [30]:
# # y_pred with DecisionTreeClassifier
# cls = DecisionTreeClassifier(random_state=42)
# cls.fit(X_train_rus, y_train_rus)
# y_pred = cls.predict(X_test)

# print(confusion_matrix(y_test, y_pred))
# print(f'Error: {zero_one_loss(y_test, y_pred)}')
# print(f'Accuracy: {accuracy_score(y_test, y_pred)}')

## Transfer Learning

Transfer learning (TL) is a research problem in machine learning (ML) that focuses on storing knowledge gained while solving one problem and applying it to a different but related problem. For example, knowledge gained while learning to recognize cars could apply when trying to recognize trucks.

https://en.wikipedia.org/wiki/Transfer_learning

## Supervised vs Unsupervised Learning

Labels or no labels

## Clustering

Clustering refers to grouping similar samples. KMeans requires knowing centroids

https://en.wikipedia.org/wiki/K-means_clustering#/media/File:K-means_convergence.gif

Determing K:

* The elbow method: https://en.wikipedia.org/wiki/Elbow_method_(clustering)
* The silhouette method: https://en.wikipedia.org/wiki/Silhouette_(clustering)

Completeness score: a cluster is complete (completeness score = 1) if all the data points belonging to the same class are clustered together

Homogeneity score: a cluster is homogeneous (homogeneity score = 1) if all the data points that are clustered together belong to the same class

V-measure: harmonic mean of completeness and homogeneity scores

https://scikit-learn.org/stable/modules/generated/sklearn.metrics.homogeneity_completeness_v_measure.html

In [31]:
# # code example
# import pandas as pd
# from sklearn.model_selection import train_test_split
# from sklearn.datasets import load_iris

# iris = load_iris()
# df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
# df['target'] = iris.target
# df['name'] = df['target'].map({0: 'setosa', 1: 'versicolor', 2: 'virginica'})

# print(df.head())

In [32]:
# # pairplot of iris
# import matplotlib.pyplot as plt
# import seaborn as sns

# # sns.set_style('whitegrid')
# colors = ['red', 'green', 'blue']
# sns.set_palette(sns.color_palette(colors))
# sns.pairplot(df.drop('target', axis=1), hue='name')
# plt.show()

In [33]:
# # plot using seaborn
# import seaborn as sns

# colors = ['red', 'green', 'blue']
# sns.set_palette(sns.color_palette(colors))
# sns.lmplot(x='sepal length (cm)', y='sepal width (cm)', data=df, hue='name', fit_reg=False);

In [34]:
# iris.target_names

In [35]:
# # plot the elbow curve
# import matplotlib.pyplot as plt
# from sklearn.cluster import KMeans

# X_values = df.drop(['target', 'name'], axis=1).values

# wcss = []
# for i in range(1, 11):
#     km = KMeans(n_clusters=i, init='k-means++', max_iter=100, n_init=10, random_state=42)
#     km.fit(X_values)
#     wcss.append(km.inertia_)

# plt.plot(range(1, 11), wcss)
# plt.title('Plotting Clusters / WCSS (the elbow method)')
# plt.xlabel('Clusters')
# plt.ylabel('WCSS')
# plt.show()

In [36]:
# # kmeans for iris

# model = KMeans(n_clusters=3, init='k-means++', max_iter=100, n_init=10, random_state=42)
# model.fit(X_values)
# y_kmeans = model.labels_

# df['cluster'] = y_kmeans

# plt.scatter(X_values[y_kmeans==0, 0], X_values[y_kmeans==0, 1], s=100, c='red', label='0')
# plt.scatter(X_values[y_kmeans==1, 0], X_values[y_kmeans==1, 1], s=100, c='green', label='1')
# plt.scatter(X_values[y_kmeans==2, 0], X_values[y_kmeans==2, 1], s=100, c='blue', label='2')

# plt.scatter(model.cluster_centers_[:, 0], model.cluster_centers_[:, 1], s=100, color='yellow', label='Centroids')
# plt.legend();

In [37]:
# fig, axes = plt.subplots(1, 2, figsize=(12, 6))

# sns.set(style='whitegrid')

# sns.scatterplot(data=df, x='sepal length (cm)', y='sepal width (cm)', hue=df['target'], ax=axes[0], palette=['red', 'green','blue'])
# sns.scatterplot(data=df, x='sepal length (cm)', y='sepal width (cm)', hue=df['cluster'], ax=axes[1], palette=['red', 'green','blue'])
# axes[0].set_title('Actual')
# axes[1].set_title('Kmeans');

In [38]:
# # try clustering for kdd99
# from sklearn.cluster import KMeans

# kmeans = KMeans(n_clusters=5).fit(X_train[continuous_features])
# y_pred = kmeans.predict(X_test[continuous_features])
# print(pd.Series(y_pred).value_counts())

In [39]:
# # get scores relating to clustering
# from sklearn.metrics import completeness_score, homogeneity_score, v_measure_score

# print(f'Completeness: {completeness_score(y_test, y_pred)}')
# print(f'Homogeneity: {homogeneity_score(y_test, y_pred)}')
# print(f'V-measure: {v_measure_score(y_test, y_pred)}')

* Completeness Score: The Completeness Score measures the extent to which all data points of a particular class are assigned to the same cluster. A high Completeness Score indicates that the clusters capture the entirety of each class, meaning all data points of a class are assigned to the same cluster.
* K-means clustering algorithm partitions a dataset into multiple clusters. If the algorithm does a good job of separating the data points into distinct groups, then the homogeneity score will be high.
* The V-measure is the harmonic mean between homogeneity and completeness: v = (1 + beta) * homogeneity * completeness / (beta * homogeneity + completeness)
* The V-measure score is really low making this unsuitable for unsupervised training so far. Class imbalance causes problems in clustering. PCA to the rescue.

## PCA

finds a set of axes (principal components) in high-dimensional space that are ordered by the variance in the data

https://en.wikipedia.org/wiki/Principal_component_analysis

In [40]:
# # current number of features (dimensions)
# print(f'Current number of features (dimensions): {len(X_train[continuous_features].columns)}')

In [41]:
# # visualize dataset with pca to reduce dimensions to 2d
# from sklearn.decomposition import PCA

# pca = PCA(n_components=3)
# X_pca = pca.fit_transform(X_train[continuous_features])

# # plt.figure(figsize=(15,10))
# colors = ['navy', 'turquoise', 'darkorange', 'red', 'purple']
# for color, cat in zip(colors, category.keys()):
#     plt.scatter(X_pca[y_train==cat, 0],
#                 X_pca[y_train==cat, 1],
#                 color=color, alpha=.8, lw=2, label=cat)

# plt.legend(loc='best', shadow=False, scatterpoints=1)

# plt.show()

We kind of see some clustering but the spread of the data makes it difficult to see defined clusters

In [42]:
# # train the data using kmeans
# kmeans = KMeans(n_clusters=5, random_state=42).fit(X_train[continuous_features])

# # get the labels
# y_kmeans = kmeans.labels_

# # plot
# colors = ['navy', 'turquoise', 'darkorange', 'red', 'purple']

# for color, cat in zip(colors, set(pd.Series(y_kmeans))):
#     plt.scatter(X_pca[y_kmeans==cat, 0],
#                 X_pca[y_kmeans==cat, 1],
#                 color=color, alpha=.8, lw=2, label=cat)

# plt.legend(loc='best', shadow=False, scatterpoints=1)

# plt.show()

## Benign vs Attack

crosstab: The pandas crosstab function builds a cross-tabulation table that can show the frequency with which certain groups of data appear. https://pbpython.com/pandas-crosstab.html

In [43]:
# y_train_attack = y_train.apply(lambda y: 'benign' if y=='benign' else 'attack')
# print(y_train_attack.value_counts())
# print(pd.crosstab(y_kmeans, y_train_attack))

We have at least one cluster with a clear majority. Create a three path strategy for dealing with each cluster:

1. For clusters that have an aggregate size of fewer than a threshold, we considert them outliers and assign them to the attack label
2. For clusters with a dominant class we assign the dominant label to the entire cluster
3. Create a classifier for the remaining clusters

### Strategy 1

Apply the dominant label

In [44]:
# # add is_attack for prediction and refit kmeans
# X_train_trimmed = X_train[continuous_features]
# X_test_trimmed = X_test[continuous_features]

# X_train_trimmed.insert(len(X_train_trimmed.columns), 'is_attack', y_train.apply(lambda y: 0 if y=='benign' else 1))
# X_test_trimmed.insert(len(X_test_trimmed.columns), 'is_attack', y_test.apply(lambda y: 0 if y=='benign' else 1))

# kmeans = KMeans(n_clusters=5, random_state=42)
# kmeans.fit(X_train_trimmed)
# y_kmeans = kmeans.labels_

In [45]:
# # apply the clusters
# y_kmeans_pred = kmeans.predict(X_test_trimmed)
# X_train_trimmed.insert(len(X_train_trimmed.columns), 'cluster', y_kmeans)
# X_test_trimmed.insert(len(X_test_trimmed.columns), 'cluster', y_kmeans_pred)

In [46]:
# # dominant label
# import numpy as np

# clstr = 0

# is_attack = X_test_trimmed[X_test_trimmed.cluster==clstr]['is_attack']
# attack_array = np.ones(len(X_test_trimmed[X_test_trimmed.cluster==clstr]))

# print(confusion_matrix(is_attack, attack_array))
# print(accuracy_score(is_attack, attack_array))

### Strategy 3

Apply a random forest classifier to label cluster

In [47]:
# # use randomforestclassifier to label cluster
# from sklearn.ensemble import RandomForestClassifier

# clstr = 3

# rfc_train = X_train_trimmed[X_train_trimmed.cluster==clstr]
# rfc_test = X_test_trimmed[X_test_trimmed.cluster==clstr]

# Xtrain = rfc_train.drop(['is_attack'], axis=1)
# ytrain = rfc_train['is_attack']
# Xtest = rfc_test.drop(['is_attack'], axis=1)
# ytest = rfc_test['is_attack']

# cls = RandomForestClassifier(n_estimators=500, max_depth=20, random_state=42)
# cls.fit(Xtrain, ytrain)
# ypred = cls.predict(Xtest)

# print(confusion_matrix(ypred, ytest))
# print(accuracy_score(ypred, ytest))

### Concerns

* Precision: proportion of the predicted items that are correctly predicted
* Recall: proportion of the actual items that are correctly predicted
* Never make adjustments to your model based on results of the test set
* Class imbalance and lack of training data
* Spend time to explore and understand the data